"""
Highly divisible triangular number

The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
"""
import math


def find_n_divisors_of(value: int) -> int:
    n_divisors = 0
    for val in range(1, math.ceil(math.sqrt(value))):
        if value % val == 0:
            n_divisors += 2
    return n_divisors


def find_triangle_number_with_more_than(n_divisors: int) -> int:
    num, triangle_numbers = 1, [1]
    while find_n_divisors_of(triangle_numbers[-1]) <= n_divisors:
        num += 1
        triangle_numbers.append(triangle_numbers[-1] + num)
    return triangle_numbers[-1]


if __name__ == "__main__":
    result = find_triangle_number_with_more_than(n_divisors=500)
    print("The value of the first triangle number to "
          f"have over five hundred divisors is {result}")
